services:
  web:
    build:
      context: ./web_victima/docker
    container_name: apache_server
    restart: always
    volumes:
      - ./web_victima/web:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - db
    env_file: ./web_victima/docker/.env.victima
    dns:
      - 8.8.8.8
      - 1.1.1.1

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: actphp  
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./web_victima/bd/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      - app_network

  hacker_db:
    image: mysql:8.0
    container_name: hacker_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: hacker_db
    ports:
      - "3307:3306"
    volumes:
      - hacker_db_data:/var/lib/mysql
      - ./web_hacker/bd/hacker_init.sql:/docker-entrypoint-initdb.d/hacker_init.sql
    networks:
      - app_network

  hacker_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hacker_phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: hacker_db
    networks:
      - app_network
    depends_on:
      - hacker_db

  python_server:
    container_name: python_server
    image: python:3.9
    restart: always
    volumes:
      - ./web_hacker/server/server.py:/app/server.py
      - ./web_hacker/docker/requirements.txt:/app/requirements.txt
    working_dir: /app
    env_file: ./web_hacker/docker/.env.hacker
    command: sh -c "pip install -r requirements.txt && python server.py"
    ports:
      - "8082:8082"
    networks:
      - app_network
    depends_on:
      - hacker_db
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  app_network:

volumes:
  db_data:
  hacker_db_data: